# Generated by Django 3.2 on 2021-04-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='slug',
            field=models.SlugField(default='Will-be-added-when-saved.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('Budget Statement', 'Budget Statement'), ('NEC & G.A Meeting', 'NEC & G.A Meeting'), ('Financial Statement', 'Financial Statement')], default='Budget', max_length=25),
        ),
    ]
