# Generated by Django 3.2 on 2021-04-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_auto_20210419_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='slug',
            field=models.SlugField(default='Will-be-added-when-saved'),
        ),
    ]
