# Generated by Django 3.2 on 2021-04-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_alter_report_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='by',
            field=models.CharField(default='', max_length=20),
        ),
    ]
