# Generated by Django 3.2 on 2021-04-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0008_auto_20210420_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='image',
            field=models.FileField(null=True, upload_to='institution_images'),
        ),
    ]
