# Generated by Django 3.2 on 2021-04-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0009_institution_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumni',
            options={'ordering': ['-year_group']},
        ),
        migrations.AddField(
            model_name='yeargroup',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
