# Generated by Django 3.2 on 2021-04-22 17:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0011_alumni_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('image', models.FileField(null=True, upload_to='patron_images')),
                ('bio', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
