# Generated by Django 3.2 on 2021-04-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0012_patron'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='occupational_role',
            field=models.CharField(default='', max_length=90),
        ),
    ]
