# Generated by Django 3.2 on 2022-01-17 16:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0015_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('image', models.FileField(null=True, upload_to='institution_images')),
                ('bio', ckeditor.fields.RichTextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='year_group',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='Patron',
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('Financial statement', 'Budget statement'), ('Research report', 'Research report'), ('Developmental report', 'Developmental report')], default='Budget', max_length=25),
        ),
        migrations.DeleteModel(
            name='Alumni',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='YearGroup',
        ),
    ]
