# Generated by Django 3.2 on 2022-01-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0016_auto_20220117_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('Financial statement', 'Financial statement'), ('Research report', 'Research report'), ('Developmental report', 'Developmental report')], default='Budget', max_length=25),
        ),
    ]
