# Generated by Django 3.2 on 2021-04-13 15:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('image', models.FileField(null=True, upload_to='post_images')),
                ('role', models.CharField(max_length=50)),
                ('bio', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
