# Generated by Django 3.2 on 2021-04-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='image',
            field=models.FileField(null=True, upload_to='leader_images'),
        ),
    ]
