# Generated by Django 3.2 on 2021-04-22 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0003_auto_20210422_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='board',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
