# Generated by Django 3.2 on 2021-04-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0004_auto_20210422_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='feature',
            field=models.BooleanField(default=False),
        ),
    ]
