# Generated by Django 3.2 on 2021-04-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0005_leader_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='slug',
            field=models.SlugField(default='will-be-added-when-saved'),
        ),
    ]
