# Generated by Django 3.2 on 2021-04-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0006_leader_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(default='will-be-added-when-saved'),
        ),
    ]
