# Generated by Django 3.2 on 2022-01-26 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0007_board_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leader',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='leader',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
